// <auto-generated />
using System;
using CodeFirst.PartTwo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.PartTwo.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20240319091236_ChangeForeignKeys")]
    partial class ChangeForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.PartTwo.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChassisNumber")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "Fiat",
                            ChassisNumber = 1234,
                            Color = "Blue",
                            Model = "Punto",
                            Year = 2001
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Volkswagen",
                            ChassisNumber = 4567,
                            Color = "Red",
                            Model = "Passat",
                            Year = 2005
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "Renault",
                            ChassisNumber = 9900,
                            Color = "Yellow",
                            Model = "Scenic",
                            Year = 2012
                        });
                });

            modelBuilder.Entity("CodeFirst.PartTwo.Models.Engine", b =>
                {
                    b.Property<int>("EngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineId"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("EngineTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("EngineId");

                    b.HasIndex("CarId")
                        .IsUnique()
                        .HasFilter("[CarId] IS NOT NULL");

                    b.HasIndex("EngineTypeId");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            EngineId = 1,
                            Brand = "Fiat",
                            CarId = 1,
                            EngineTypeId = 1,
                            SerialNumber = "000000",
                            Type = "type1",
                            Year = 2001
                        },
                        new
                        {
                            EngineId = 2,
                            Brand = "Volkswagen",
                            CarId = 2,
                            EngineTypeId = 1,
                            SerialNumber = "000001",
                            Type = "type2",
                            Year = 2005
                        },
                        new
                        {
                            EngineId = 3,
                            Brand = "Renault",
                            CarId = 3,
                            EngineTypeId = 2,
                            SerialNumber = "000002",
                            Type = "type3",
                            Year = 2012
                        });
                });

            modelBuilder.Entity("CodeFirst.PartTwo.Models.EngineType", b =>
                {
                    b.Property<int>("EngineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineTypeId"));

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EngineTypeId");

                    b.ToTable("EngineTypes");

                    b.HasData(
                        new
                        {
                            EngineTypeId = 1,
                            Model = "Model1",
                            Name = "Name1"
                        },
                        new
                        {
                            EngineTypeId = 2,
                            Model = "Model2",
                            Name = "Name2"
                        });
                });

            modelBuilder.Entity("CodeFirst.PartTwo.Models.Engine", b =>
                {
                    b.HasOne("CodeFirst.PartTwo.Models.Car", "Car")
                        .WithOne("Engine")
                        .HasForeignKey("CodeFirst.PartTwo.Models.Engine", "CarId");

                    b.HasOne("CodeFirst.PartTwo.Models.EngineType", "EngineType")
                        .WithMany("Engines")
                        .HasForeignKey("EngineTypeId");

                    b.Navigation("Car");

                    b.Navigation("EngineType");
                });

            modelBuilder.Entity("CodeFirst.PartTwo.Models.Car", b =>
                {
                    b.Navigation("Engine");
                });

            modelBuilder.Entity("CodeFirst.PartTwo.Models.EngineType", b =>
                {
                    b.Navigation("Engines");
                });
#pragma warning restore 612, 618
        }
    }
}
